/*
 * XI Sdk Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvoiceDetailsv61ResponseSummaryTotals
 */
public class InvoiceDetailsv61ResponseSummaryTotalsTest {
    private final InvoiceDetailsv61ResponseSummaryTotals model = new InvoiceDetailsv61ResponseSummaryTotals();

    /**
     * Model tests for InvoiceDetailsv61ResponseSummaryTotals
     */
    @Test
    public void testInvoiceDetailsv61ResponseSummaryTotals() {
        // TODO: test InvoiceDetailsv61ResponseSummaryTotals
    }

    /**
     * Test the property 'netInvoiceAmount'
     */
    @Test
    public void netInvoiceAmountTest() {
        // TODO: test netInvoiceAmount
    }

    /**
     * Test the property 'discountAmount'
     */
    @Test
    public void discountAmountTest() {
        // TODO: test discountAmount
    }

    /**
     * Test the property 'discountType'
     */
    @Test
    public void discountTypeTest() {
        // TODO: test discountType
    }

    /**
     * Test the property 'totalTaxAmount'
     */
    @Test
    public void totalTaxAmountTest() {
        // TODO: test totalTaxAmount
    }

    /**
     * Test the property 'invoicedAmountDue'
     */
    @Test
    public void invoicedAmountDueTest() {
        // TODO: test invoicedAmountDue
    }

    /**
     * Test the property 'freightAmount'
     */
    @Test
    public void freightAmountTest() {
        // TODO: test freightAmount
    }

}
