/*
 * XI SDK Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvoiceSearchResponseInvoicesInner
 */
public class InvoiceSearchResponseInvoicesInnerTest {
    private final InvoiceSearchResponseInvoicesInner model = new InvoiceSearchResponseInvoicesInner();

    /**
     * Model tests for InvoiceSearchResponseInvoicesInner
     */
    @Test
    public void testInvoiceSearchResponseInvoicesInner() {
        // TODO: test InvoiceSearchResponseInvoicesInner
    }

    /**
     * Test the property 'paymentTermsDueDate'
     */
    @Test
    public void paymentTermsDueDateTest() {
        // TODO: test paymentTermsDueDate
    }

    /**
     * Test the property 'erpOrderNumber'
     */
    @Test
    public void erpOrderNumberTest() {
        // TODO: test erpOrderNumber
    }

    /**
     * Test the property 'invoiceNumber'
     */
    @Test
    public void invoiceNumberTest() {
        // TODO: test invoiceNumber
    }

    /**
     * Test the property 'invoiceStatus'
     */
    @Test
    public void invoiceStatusTest() {
        // TODO: test invoiceStatus
    }

    /**
     * Test the property 'invoiceDate'
     */
    @Test
    public void invoiceDateTest() {
        // TODO: test invoiceDate
    }

    /**
     * Test the property 'invoiceDueDate'
     */
    @Test
    public void invoiceDueDateTest() {
        // TODO: test invoiceDueDate
    }

    /**
     * Test the property 'invoicedAmountDue'
     */
    @Test
    public void invoicedAmountDueTest() {
        // TODO: test invoicedAmountDue
    }

    /**
     * Test the property 'customerOrderNumber'
     */
    @Test
    public void customerOrderNumberTest() {
        // TODO: test customerOrderNumber
    }

    /**
     * Test the property 'orderCreateDate'
     */
    @Test
    public void orderCreateDateTest() {
        // TODO: test orderCreateDate
    }

    /**
     * Test the property 'endCustomerOrderNumber'
     */
    @Test
    public void endCustomerOrderNumberTest() {
        // TODO: test endCustomerOrderNumber
    }

    /**
     * Test the property 'invoiceAmountInclTax'
     */
    @Test
    public void invoiceAmountInclTaxTest() {
        // TODO: test invoiceAmountInclTax
    }

}
