/*
 * XI Sdk Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvoiceDetailsv61ResponseLinesInnerSerialNumbersInner
 */
public class InvoiceDetailsv61ResponseLinesInnerSerialNumbersInnerTest {
    private final InvoiceDetailsv61ResponseLinesInnerSerialNumbersInner model = new InvoiceDetailsv61ResponseLinesInnerSerialNumbersInner();

    /**
     * Model tests for InvoiceDetailsv61ResponseLinesInnerSerialNumbersInner
     */
    @Test
    public void testInvoiceDetailsv61ResponseLinesInnerSerialNumbersInner() {
        // TODO: test InvoiceDetailsv61ResponseLinesInnerSerialNumbersInner
    }

    /**
     * Test the property 'serialNumber'
     */
    @Test
    public void serialNumberTest() {
        // TODO: test serialNumber
    }

}
