/*
 * Reseller API
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderCreateResponseServiceresponseOrdercreateresponseInnerLinesInner
 */
public class OrderCreateResponseServiceresponseOrdercreateresponseInnerLinesInnerTest {
    private final OrderCreateResponseServiceresponseOrdercreateresponseInnerLinesInner model = new OrderCreateResponseServiceresponseOrdercreateresponseInnerLinesInner();

    /**
     * Model tests for OrderCreateResponseServiceresponseOrdercreateresponseInnerLinesInner
     */
    @Test
    public void testOrderCreateResponseServiceresponseOrdercreateresponseInnerLinesInner() {
        // TODO: test OrderCreateResponseServiceresponseOrdercreateresponseInnerLinesInner
    }

    /**
     * Test the property 'linetype'
     */
    @Test
    public void linetypeTest() {
        // TODO: test linetype
    }

    /**
     * Test the property 'globallinenumber'
     */
    @Test
    public void globallinenumberTest() {
        // TODO: test globallinenumber
    }

    /**
     * Test the property 'partnumber'
     */
    @Test
    public void partnumberTest() {
        // TODO: test partnumber
    }

    /**
     * Test the property 'globalskuid'
     */
    @Test
    public void globalskuidTest() {
        // TODO: test globalskuid
    }

    /**
     * Test the property 'linenumber'
     */
    @Test
    public void linenumberTest() {
        // TODO: test linenumber
    }

    /**
     * Test the property 'carriercode'
     */
    @Test
    public void carriercodeTest() {
        // TODO: test carriercode
    }

    /**
     * Test the property 'carrierdescription'
     */
    @Test
    public void carrierdescriptionTest() {
        // TODO: test carrierdescription
    }

    /**
     * Test the property 'requestedunitprice'
     */
    @Test
    public void requestedunitpriceTest() {
        // TODO: test requestedunitprice
    }

    /**
     * Test the property 'requestedquantity'
     */
    @Test
    public void requestedquantityTest() {
        // TODO: test requestedquantity
    }

    /**
     * Test the property 'confirmedquantity'
     */
    @Test
    public void confirmedquantityTest() {
        // TODO: test confirmedquantity
    }

    /**
     * Test the property 'backorderedquantity'
     */
    @Test
    public void backorderedquantityTest() {
        // TODO: test backorderedquantity
    }

    /**
     * Test the property 'unitproductprice'
     */
    @Test
    public void unitproductpriceTest() {
        // TODO: test unitproductprice
    }

    /**
     * Test the property 'netamount'
     */
    @Test
    public void netamountTest() {
        // TODO: test netamount
    }

    /**
     * Test the property 'warehouseid'
     */
    @Test
    public void warehouseidTest() {
        // TODO: test warehouseid
    }

    /**
     * Test the property 'ordersuffix'
     */
    @Test
    public void ordersuffixTest() {
        // TODO: test ordersuffix
    }

}
