/*
 * XI Sdk Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import xiresellers.client.model.OrderModifyResponseServiceresponseOrdermodifyresponse;
import xiresellers.client.model.OrderModifyResponseServiceresponseResponsepreamble;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderModifyResponseServiceresponse
 */
public class OrderModifyResponseServiceresponseTest {
    private final OrderModifyResponseServiceresponse model = new OrderModifyResponseServiceresponse();

    /**
     * Model tests for OrderModifyResponseServiceresponse
     */
    @Test
    public void testOrderModifyResponseServiceresponse() {
        // TODO: test OrderModifyResponseServiceresponse
    }

    /**
     * Test the property 'responsepreamble'
     */
    @Test
    public void responsepreambleTest() {
        // TODO: test responsepreamble
    }

    /**
     * Test the property 'ordermodifyresponse'
     */
    @Test
    public void ordermodifyresponseTest() {
        // TODO: test ordermodifyresponse
    }

}
