/*
 * Reseller API
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderModifyResponseServiceresponseOrdermodifyresponse
 */
public class OrderModifyResponseServiceresponseOrdermodifyresponseTest {
    private final OrderModifyResponseServiceresponseOrdermodifyresponse model = new OrderModifyResponseServiceresponseOrdermodifyresponse();

    /**
     * Model tests for OrderModifyResponseServiceresponseOrdermodifyresponse
     */
    @Test
    public void testOrderModifyResponseServiceresponseOrdermodifyresponse() {
        // TODO: test OrderModifyResponseServiceresponseOrdermodifyresponse
    }

    /**
     * Test the property 'responseflag'
     */
    @Test
    public void responseflagTest() {
        // TODO: test responseflag
    }

    /**
     * Test the property 'errortype'
     */
    @Test
    public void errortypeTest() {
        // TODO: test errortype
    }

    /**
     * Test the property 'acktriggered'
     */
    @Test
    public void acktriggeredTest() {
        // TODO: test acktriggered
    }

    /**
     * Test the property 'warncode'
     */
    @Test
    public void warncodeTest() {
        // TODO: test warncode
    }

    /**
     * Test the property 'headerresponse'
     */
    @Test
    public void headerresponseTest() {
        // TODO: test headerresponse
    }

}
