/*
 * Reseller API
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import xiresellers.client.model.OrderSearchResponseServiceResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderSearchResponse
 */
public class OrderSearchResponseTest {
    private final OrderSearchResponse model = new OrderSearchResponse();

    /**
     * Model tests for OrderSearchResponse
     */
    @Test
    public void testOrderSearchResponse() {
        // TODO: test OrderSearchResponse
    }

    /**
     * Test the property 'serviceResponse'
     */
    @Test
    public void serviceResponseTest() {
        // TODO: test serviceResponse
    }

}
