/*
 * XI Sdk Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import xiresellers.client.model.InvoiceDetailResponseServiceresponseResponsepreamble;
import xiresellers.client.model.OrderDetailResponseServiceresponseOrderdetailresponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderDetailResponseServiceresponse
 */
public class OrderDetailResponseServiceresponseTest {
    private final OrderDetailResponseServiceresponse model = new OrderDetailResponseServiceresponse();

    /**
     * Model tests for OrderDetailResponseServiceresponse
     */
    @Test
    public void testOrderDetailResponseServiceresponse() {
        // TODO: test OrderDetailResponseServiceresponse
    }

    /**
     * Test the property 'responsepreamble'
     */
    @Test
    public void responsepreambleTest() {
        // TODO: test responsepreamble
    }

    /**
     * Test the property 'orderdetailresponse'
     */
    @Test
    public void orderdetailresponseTest() {
        // TODO: test orderdetailresponse
    }

}
