/*
 * XI SDK Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderCreateResponseOrdersInnerRejectedLineItemsInner
 */
public class OrderCreateResponseOrdersInnerRejectedLineItemsInnerTest {
    private final OrderCreateResponseOrdersInnerRejectedLineItemsInner model = new OrderCreateResponseOrdersInnerRejectedLineItemsInner();

    /**
     * Model tests for OrderCreateResponseOrdersInnerRejectedLineItemsInner
     */
    @Test
    public void testOrderCreateResponseOrdersInnerRejectedLineItemsInner() {
        // TODO: test OrderCreateResponseOrdersInnerRejectedLineItemsInner
    }

    /**
     * Test the property 'customerLinenumber'
     */
    @Test
    public void customerLinenumberTest() {
        // TODO: test customerLinenumber
    }

    /**
     * Test the property 'ingramPartNumber'
     */
    @Test
    public void ingramPartNumberTest() {
        // TODO: test ingramPartNumber
    }

    /**
     * Test the property 'vendorPartNumber'
     */
    @Test
    public void vendorPartNumberTest() {
        // TODO: test vendorPartNumber
    }

    /**
     * Test the property 'quantityOrdered'
     */
    @Test
    public void quantityOrderedTest() {
        // TODO: test quantityOrdered
    }

    /**
     * Test the property 'rejectCode'
     */
    @Test
    public void rejectCodeTest() {
        // TODO: test rejectCode
    }

    /**
     * Test the property 'rejectReason'
     */
    @Test
    public void rejectReasonTest() {
        // TODO: test rejectReason
    }

}
