/*
 * Reseller API
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import xiresellers.client.model.OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduser;
import xiresellers.client.model.OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInner
 */
public class OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerTest {
    private final OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInner model = new OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInner();

    /**
     * Model tests for OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInner
     */
    @Test
    public void testOrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInner() {
        // TODO: test OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInner
    }

    /**
     * Test the property 'linetype'
     */
    @Test
    public void linetypeTest() {
        // TODO: test linetype
    }

    /**
     * Test the property 'linenumber'
     */
    @Test
    public void linenumberTest() {
        // TODO: test linenumber
    }

    /**
     * Test the property 'ingrampartnumber'
     */
    @Test
    public void ingrampartnumberTest() {
        // TODO: test ingrampartnumber
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'vendorpartnumber'
     */
    @Test
    public void vendorpartnumberTest() {
        // TODO: test vendorpartnumber
    }

    /**
     * Test the property 'customerpartnumber'
     */
    @Test
    public void customerpartnumberTest() {
        // TODO: test customerpartnumber
    }

    /**
     * Test the property 'upCCode'
     */
    @Test
    public void upCCodeTest() {
        // TODO: test upCCode
    }

    /**
     * Test the property 'warehouseid'
     */
    @Test
    public void warehouseidTest() {
        // TODO: test warehouseid
    }

    /**
     * Test the property 'unitprice'
     */
    @Test
    public void unitpriceTest() {
        // TODO: test unitprice
    }

    /**
     * Test the property 'enduser'
     */
    @Test
    public void enduserTest() {
        // TODO: test enduser
    }

    /**
     * Test the property 'productextendedspecs'
     */
    @Test
    public void productextendedspecsTest() {
        // TODO: test productextendedspecs
    }

}
