/*
 * XI Sdk Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import xiresellers.client.model.OrderDetailResponseServiceresponseOrderdetailresponseBilltoaddress;
import xiresellers.client.model.OrderDetailResponseServiceresponseOrderdetailresponseCommentlinesInner;
import xiresellers.client.model.OrderDetailResponseServiceresponseOrderdetailresponseEnduserinfo;
import xiresellers.client.model.OrderDetailResponseServiceresponseOrderdetailresponseExtendedspecsInner;
import xiresellers.client.model.OrderDetailResponseServiceresponseOrderdetailresponseLinesInner;
import xiresellers.client.model.OrderDetailResponseServiceresponseOrderdetailresponseMiscfeelineInner;
import xiresellers.client.model.OrderDetailResponseServiceresponseOrderdetailresponseShiptoaddress;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderDetailResponseServiceresponseOrderdetailresponse
 */
public class OrderDetailResponseServiceresponseOrderdetailresponseTest {
    private final OrderDetailResponseServiceresponseOrderdetailresponse model = new OrderDetailResponseServiceresponseOrderdetailresponse();

    /**
     * Model tests for OrderDetailResponseServiceresponseOrderdetailresponse
     */
    @Test
    public void testOrderDetailResponseServiceresponseOrderdetailresponse() {
        // TODO: test OrderDetailResponseServiceresponseOrderdetailresponse
    }

    /**
     * Test the property 'ordernumber'
     */
    @Test
    public void ordernumberTest() {
        // TODO: test ordernumber
    }

    /**
     * Test the property 'ordertype'
     */
    @Test
    public void ordertypeTest() {
        // TODO: test ordertype
    }

    /**
     * Test the property 'customerordernumber'
     */
    @Test
    public void customerordernumberTest() {
        // TODO: test customerordernumber
    }

    /**
     * Test the property 'enduserponumber'
     */
    @Test
    public void enduserponumberTest() {
        // TODO: test enduserponumber
    }

    /**
     * Test the property 'orderstatus'
     */
    @Test
    public void orderstatusTest() {
        // TODO: test orderstatus
    }

    /**
     * Test the property 'entrytimestamp'
     */
    @Test
    public void entrytimestampTest() {
        // TODO: test entrytimestamp
    }

    /**
     * Test the property 'entrymethoddescription'
     */
    @Test
    public void entrymethoddescriptionTest() {
        // TODO: test entrymethoddescription
    }

    /**
     * Test the property 'ordertotalvalue'
     */
    @Test
    public void ordertotalvalueTest() {
        // TODO: test ordertotalvalue
    }

    /**
     * Test the property 'ordersubtotal'
     */
    @Test
    public void ordersubtotalTest() {
        // TODO: test ordersubtotal
    }

    /**
     * Test the property 'freightamount'
     */
    @Test
    public void freightamountTest() {
        // TODO: test freightamount
    }

    /**
     * Test the property 'currencycode'
     */
    @Test
    public void currencycodeTest() {
        // TODO: test currencycode
    }

    /**
     * Test the property 'totalweight'
     */
    @Test
    public void totalweightTest() {
        // TODO: test totalweight
    }

    /**
     * Test the property 'totaltax'
     */
    @Test
    public void totaltaxTest() {
        // TODO: test totaltax
    }

    /**
     * Test the property 'billtoaddress'
     */
    @Test
    public void billtoaddressTest() {
        // TODO: test billtoaddress
    }

    /**
     * Test the property 'shiptoaddress'
     */
    @Test
    public void shiptoaddressTest() {
        // TODO: test shiptoaddress
    }

    /**
     * Test the property 'enduserinfo'
     */
    @Test
    public void enduserinfoTest() {
        // TODO: test enduserinfo
    }

    /**
     * Test the property 'lines'
     */
    @Test
    public void linesTest() {
        // TODO: test lines
    }

    /**
     * Test the property 'commentlines'
     */
    @Test
    public void commentlinesTest() {
        // TODO: test commentlines
    }

    /**
     * Test the property 'miscfeeline'
     */
    @Test
    public void miscfeelineTest() {
        // TODO: test miscfeeline
    }

    /**
     * Test the property 'extendedspecs'
     */
    @Test
    public void extendedspecsTest() {
        // TODO: test extendedspecs
    }

}
