/*
 * XI SDK Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderModifyResponseServiceresponseResponsepreamble
 */
public class OrderModifyResponseServiceresponseResponsepreambleTest {
    private final OrderModifyResponseServiceresponseResponsepreamble model = new OrderModifyResponseServiceresponseResponsepreamble();

    /**
     * Model tests for OrderModifyResponseServiceresponseResponsepreamble
     */
    @Test
    public void testOrderModifyResponseServiceresponseResponsepreamble() {
        // TODO: test OrderModifyResponseServiceresponseResponsepreamble
    }

    /**
     * Test the property 'responsestatus'
     */
    @Test
    public void responsestatusTest() {
        // TODO: test responsestatus
    }

    /**
     * Test the property 'responsemessage'
     */
    @Test
    public void responsemessageTest() {
        // TODO: test responsemessage
    }

}
