/*
 * XI Sdk Resellers
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PriceAndAvailabilityRequestProductsInnerQuantityRequested
 */
public class PriceAndAvailabilityRequestProductsInnerQuantityRequestedTest {
    private final PriceAndAvailabilityRequestProductsInnerQuantityRequested model = new PriceAndAvailabilityRequestProductsInnerQuantityRequested();

    /**
     * Model tests for PriceAndAvailabilityRequestProductsInnerQuantityRequested
     */
    @Test
    public void testPriceAndAvailabilityRequestProductsInnerQuantityRequested() {
        // TODO: test PriceAndAvailabilityRequestProductsInnerQuantityRequested
    }

}
