/*
 * XI SDK Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import xiresellers.client.model.InvoiceDetailResponseServiceresponseInvoicedetailresponseExtendedspecsInner;
import xiresellers.client.model.ProductLineTypeSerialnumberdetailsInner;
import xiresellers.client.model.ProductLineTypeTrackingnumberdetailsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductLineType
 */
public class ProductLineTypeTest {
    private final ProductLineType model = new ProductLineType();

    /**
     * Model tests for ProductLineType
     */
    @Test
    public void testProductLineType() {
        // TODO: test ProductLineType
    }

    /**
     * Test the property 'linenumber'
     */
    @Test
    public void linenumberTest() {
        // TODO: test linenumber
    }

    /**
     * Test the property 'linetype'
     */
    @Test
    public void linetypeTest() {
        // TODO: test linetype
    }

    /**
     * Test the property 'partnumber'
     */
    @Test
    public void partnumberTest() {
        // TODO: test partnumber
    }

    /**
     * Test the property 'vendorpartnumber'
     */
    @Test
    public void vendorpartnumberTest() {
        // TODO: test vendorpartnumber
    }

    /**
     * Test the property 'partdescription'
     */
    @Test
    public void partdescriptionTest() {
        // TODO: test partdescription
    }

    /**
     * Test the property 'shipfrombranch'
     */
    @Test
    public void shipfrombranchTest() {
        // TODO: test shipfrombranch
    }

    /**
     * Test the property 'shippedquantity'
     */
    @Test
    public void shippedquantityTest() {
        // TODO: test shippedquantity
    }

    /**
     * Test the property 'orderedquantity'
     */
    @Test
    public void orderedquantityTest() {
        // TODO: test orderedquantity
    }

    /**
     * Test the property 'marginpercent'
     */
    @Test
    public void marginpercentTest() {
        // TODO: test marginpercent
    }

    /**
     * Test the property 'backorderquantity'
     */
    @Test
    public void backorderquantityTest() {
        // TODO: test backorderquantity
    }

    /**
     * Test the property 'backorderetadate'
     */
    @Test
    public void backorderetadateTest() {
        // TODO: test backorderetadate
    }

    /**
     * Test the property 'extendedprice'
     */
    @Test
    public void extendedpriceTest() {
        // TODO: test extendedprice
    }

    /**
     * Test the property 'specialbidnumber'
     */
    @Test
    public void specialbidnumberTest() {
        // TODO: test specialbidnumber
    }

    /**
     * Test the property 'ordersuffix'
     */
    @Test
    public void ordersuffixTest() {
        // TODO: test ordersuffix
    }

    /**
     * Test the property 'isacopapplied'
     */
    @Test
    public void isacopappliedTest() {
        // TODO: test isacopapplied
    }

    /**
     * Test the property 'unitprice'
     */
    @Test
    public void unitpriceTest() {
        // TODO: test unitprice
    }

    /**
     * Test the property 'unitofmeasure'
     */
    @Test
    public void unitofmeasureTest() {
        // TODO: test unitofmeasure
    }

    /**
     * Test the property 'serialnumberdetails'
     */
    @Test
    public void serialnumberdetailsTest() {
        // TODO: test serialnumberdetails
    }

    /**
     * Test the property 'trackingnumberdetails'
     */
    @Test
    public void trackingnumberdetailsTest() {
        // TODO: test trackingnumberdetails
    }

    /**
     * Test the property 'productextendedspecs'
     */
    @Test
    public void productextendedspecsTest() {
        // TODO: test productextendedspecs
    }

}
