/*
 * Reseller API
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QuoteToOrderResponse
 */
public class QuoteToOrderResponseTest {
    private final QuoteToOrderResponse model = new QuoteToOrderResponse();

    /**
     * Model tests for QuoteToOrderResponse
     */
    @Test
    public void testQuoteToOrderResponse() {
        // TODO: test QuoteToOrderResponse
    }

    /**
     * Test the property 'quoteNumber'
     */
    @Test
    public void quoteNumberTest() {
        // TODO: test quoteNumber
    }

    /**
     * Test the property 'confirmationNumber'
     */
    @Test
    public void confirmationNumberTest() {
        // TODO: test confirmationNumber
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
