/*
 * XI Sdk Resellers
 * For Ingram Micro Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RenewalsSearchRequestDateTypeEndDate
 */
public class RenewalsSearchRequestDateTypeEndDateTest {
    private final RenewalsSearchRequestDateTypeEndDate model = new RenewalsSearchRequestDateTypeEndDate();

    /**
     * Model tests for RenewalsSearchRequestDateTypeEndDate
     */
    @Test
    public void testRenewalsSearchRequestDateTypeEndDate() {
        // TODO: test RenewalsSearchRequestDateTypeEndDate
    }

    /**
     * Test the property 'customStartDate'
     */
    @Test
    public void customStartDateTest() {
        // TODO: test customStartDate
    }

    /**
     * Test the property 'customEndDate'
     */
    @Test
    public void customEndDateTest() {
        // TODO: test customEndDate
    }

}
