/*
 * Reseller API Documentation
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.InvoiceDetailResponseServiceresponseInvoicedetailresponse;
import org.openapitools.client.model.InvoiceDetailResponseServiceresponseResponsepreamble;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvoiceDetailResponseServiceresponse
 */
public class InvoiceDetailResponseServiceresponseTest {
    private final InvoiceDetailResponseServiceresponse model = new InvoiceDetailResponseServiceresponse();

    /**
     * Model tests for InvoiceDetailResponseServiceresponse
     */
    @Test
    public void testInvoiceDetailResponseServiceresponse() {
        // TODO: test InvoiceDetailResponseServiceresponse
    }

    /**
     * Test the property 'responsepreamble'
     */
    @Test
    public void responsepreambleTest() {
        // TODO: test responsepreamble
    }

    /**
     * Test the property 'invoicedetailresponse'
     */
    @Test
    public void invoicedetailresponseTest() {
        // TODO: test invoicedetailresponse
    }

}
