/*
 * Reseller API Documentation
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.OrderDeleteRequestServicerequestOrderDeleteRequestDetails;
import org.openapitools.client.model.OrderDeleteRequestServicerequestRequestpreamble;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderDeleteRequestServicerequest
 */
public class OrderDeleteRequestServicerequestTest {
    private final OrderDeleteRequestServicerequest model = new OrderDeleteRequestServicerequest();

    /**
     * Model tests for OrderDeleteRequestServicerequest
     */
    @Test
    public void testOrderDeleteRequestServicerequest() {
        // TODO: test OrderDeleteRequestServicerequest
    }

    /**
     * Test the property 'requestpreamble'
     */
    @Test
    public void requestpreambleTest() {
        // TODO: test requestpreamble
    }

    /**
     * Test the property 'orderDeleteRequestDetails'
     */
    @Test
    public void orderDeleteRequestDetailsTest() {
        // TODO: test orderDeleteRequestDetails
    }

}
