/*
 * Reseller API Documentation
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PriceAndAvailabilityResponseInnerAvailabilityAvailabilityByWarehouseInnerBackOrderInfoInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PriceAndAvailabilityResponseInnerAvailabilityAvailabilityByWarehouseInner
 */
public class PriceAndAvailabilityResponseInnerAvailabilityAvailabilityByWarehouseInnerTest {
    private final PriceAndAvailabilityResponseInnerAvailabilityAvailabilityByWarehouseInner model = new PriceAndAvailabilityResponseInnerAvailabilityAvailabilityByWarehouseInner();

    /**
     * Model tests for PriceAndAvailabilityResponseInnerAvailabilityAvailabilityByWarehouseInner
     */
    @Test
    public void testPriceAndAvailabilityResponseInnerAvailabilityAvailabilityByWarehouseInner() {
        // TODO: test PriceAndAvailabilityResponseInnerAvailabilityAvailabilityByWarehouseInner
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'warehouseId'
     */
    @Test
    public void warehouseIdTest() {
        // TODO: test warehouseId
    }

    /**
     * Test the property 'quantityAvailable'
     */
    @Test
    public void quantityAvailableTest() {
        // TODO: test quantityAvailable
    }

    /**
     * Test the property 'quantityBackordered'
     */
    @Test
    public void quantityBackorderedTest() {
        // TODO: test quantityBackordered
    }

    /**
     * Test the property 'quantityBackorderedEta'
     */
    @Test
    public void quantityBackorderedEtaTest() {
        // TODO: test quantityBackorderedEta
    }

    /**
     * Test the property 'backOrderInfo'
     */
    @Test
    public void backOrderInfoTest() {
        // TODO: test backOrderInfo
    }

}
