/*
 * XI Sdk Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.api;

import xiresellers.client.ApiException;
import xiresellers.client.model.InvoiceDetailRequest;
import xiresellers.client.model.InvoiceDetailResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InvoicesV4Api
 */
@Disabled
public class InvoicesV4ApiTest {

    private final InvoicesV4Api api = new InvoicesV4Api();

    /**
     * Get Invoice Details
     *
     * A real-time request that allows the customer to query Ingram Micro for Invoice information for a specific open or shipped order (in the past 9 months). Orders are searched using Ingram Micro Sales Order Number.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postV4InvoicedetailsTest() throws ApiException {
        InvoiceDetailRequest invoiceDetailRequest = null;
        InvoiceDetailResponse response = api.postV4Invoicedetails(invoiceDetailRequest);
        // TODO: test validations
    }

}
