/*
 * XI Sdk Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.api;

import xiresellers.client.ApiException;
import xiresellers.client.model.QuoteDetails;
import xiresellers.client.model.QuoteListRequest;
import xiresellers.client.model.QuoteListResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QuotesV5Api
 */
@Disabled
public class QuotesV5ApiTest {

    private final QuotesV5Api api = new QuotesV5Api();

    /**
     * Get Quote Details
     *
     * The quote details API provides all quote details associated with the quote number provided.   The “&lt;strong&gt;quoteNumber&lt;/strong&gt;”, “&lt;strong&gt;isoCountryCode&lt;/strong&gt;” and “&lt;strong&gt;customerNumber&lt;/strong&gt;” parameters are required.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getV5QuotesDetailsTest() throws ApiException {
        String quoteNumber = null;
        String customerNumber = null;
        String isoCountryCode = null;
        String thirdPartySource = null;
        QuoteDetails response = api.getV5QuotesDetails(quoteNumber, customerNumber, isoCountryCode, thirdPartySource);
        // TODO: test validations
    }

    /**
     * Search Quotes
     *
     * This endpoint enables the retrieval and filtering of relevant quote list key criteria data, such as quote number, special bid numbers, end user name, status, and date ranges from the Ingram Micro system. By default, the Quotes endpoint retrieves quotes modified or created within the last 30 days.   Observe these additional parameters:&lt;ul&gt;&lt;li&gt;Only active quotes are available through this API.&lt;/li&gt;&lt;li&gt;Quotes older than 365 days are excluded by default.&lt;/li&gt;&lt;li&gt;You can use date range filters to retrieve quotes older than 30 days and up to 365 days.&lt;/li&gt;&lt;li&gt;Quotes that are in draft and closed states are excluded, and are not accessible through this API.&lt;/li&gt;&lt;/ul&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postV5QuotesSearchTest() throws ApiException {
        QuoteListRequest quoteListRequest = null;
        QuoteListResponse response = api.postV5QuotesSearch(quoteListRequest);
        // TODO: test validations
    }

}
