/*
 * Reseller API Documentation
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PriceAndAvailabilityRequestServicerequestPriceandstockrequest;
import org.openapitools.client.model.PriceAndAvailabilityRequestServicerequestRequestpreamble;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PriceAndAvailabilityRequestServicerequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-11T06:39:09.782810Z[Etc/UTC]")
public class PriceAndAvailabilityRequestServicerequest {
  public static final String SERIALIZED_NAME_REQUESTPREAMBLE = "requestpreamble";
  @SerializedName(SERIALIZED_NAME_REQUESTPREAMBLE)
  private PriceAndAvailabilityRequestServicerequestRequestpreamble requestpreamble;

  public static final String SERIALIZED_NAME_PRICEANDSTOCKREQUEST = "priceandstockrequest";
  @SerializedName(SERIALIZED_NAME_PRICEANDSTOCKREQUEST)
  private PriceAndAvailabilityRequestServicerequestPriceandstockrequest priceandstockrequest;

  public PriceAndAvailabilityRequestServicerequest() {
  }

  public PriceAndAvailabilityRequestServicerequest requestpreamble(PriceAndAvailabilityRequestServicerequestRequestpreamble requestpreamble) {
    this.requestpreamble = requestpreamble;
    return this;
  }

   /**
   * Get requestpreamble
   * @return requestpreamble
  **/
  @javax.annotation.Nullable
  public PriceAndAvailabilityRequestServicerequestRequestpreamble getRequestpreamble() {
    return requestpreamble;
  }

  public void setRequestpreamble(PriceAndAvailabilityRequestServicerequestRequestpreamble requestpreamble) {
    this.requestpreamble = requestpreamble;
  }


  public PriceAndAvailabilityRequestServicerequest priceandstockrequest(PriceAndAvailabilityRequestServicerequestPriceandstockrequest priceandstockrequest) {
    this.priceandstockrequest = priceandstockrequest;
    return this;
  }

   /**
   * Get priceandstockrequest
   * @return priceandstockrequest
  **/
  @javax.annotation.Nullable
  public PriceAndAvailabilityRequestServicerequestPriceandstockrequest getPriceandstockrequest() {
    return priceandstockrequest;
  }

  public void setPriceandstockrequest(PriceAndAvailabilityRequestServicerequestPriceandstockrequest priceandstockrequest) {
    this.priceandstockrequest = priceandstockrequest;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceAndAvailabilityRequestServicerequest priceAndAvailabilityRequestServicerequest = (PriceAndAvailabilityRequestServicerequest) o;
    return Objects.equals(this.requestpreamble, priceAndAvailabilityRequestServicerequest.requestpreamble) &&
        Objects.equals(this.priceandstockrequest, priceAndAvailabilityRequestServicerequest.priceandstockrequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestpreamble, priceandstockrequest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceAndAvailabilityRequestServicerequest {\n");
    sb.append("    requestpreamble: ").append(toIndentedString(requestpreamble)).append("\n");
    sb.append("    priceandstockrequest: ").append(toIndentedString(priceandstockrequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("requestpreamble");
    openapiFields.add("priceandstockrequest");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PriceAndAvailabilityRequestServicerequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PriceAndAvailabilityRequestServicerequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PriceAndAvailabilityRequestServicerequest is not found in the empty JSON string", PriceAndAvailabilityRequestServicerequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PriceAndAvailabilityRequestServicerequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PriceAndAvailabilityRequestServicerequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `requestpreamble`
      if (jsonObj.get("requestpreamble") != null && !jsonObj.get("requestpreamble").isJsonNull()) {
        PriceAndAvailabilityRequestServicerequestRequestpreamble.validateJsonElement(jsonObj.get("requestpreamble"));
      }
      // validate the optional field `priceandstockrequest`
      if (jsonObj.get("priceandstockrequest") != null && !jsonObj.get("priceandstockrequest").isJsonNull()) {
        PriceAndAvailabilityRequestServicerequestPriceandstockrequest.validateJsonElement(jsonObj.get("priceandstockrequest"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PriceAndAvailabilityRequestServicerequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PriceAndAvailabilityRequestServicerequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PriceAndAvailabilityRequestServicerequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PriceAndAvailabilityRequestServicerequest.class));

       return (TypeAdapter<T>) new TypeAdapter<PriceAndAvailabilityRequestServicerequest>() {
           @Override
           public void write(JsonWriter out, PriceAndAvailabilityRequestServicerequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PriceAndAvailabilityRequestServicerequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PriceAndAvailabilityRequestServicerequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PriceAndAvailabilityRequestServicerequest
  * @throws IOException if the JSON string is invalid with respect to PriceAndAvailabilityRequestServicerequest
  */
  public static PriceAndAvailabilityRequestServicerequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PriceAndAvailabilityRequestServicerequest.class);
  }

 /**
  * Convert an instance of PriceAndAvailabilityRequestServicerequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

