/*
 * XI Sdk Resellers
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import xiresellers.client.JSON;

/**
 * AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-04T13:12:48.606866Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner {
  public static final String SERIALIZED_NAME_DATE_OF_PURCHASE = "dateOfPurchase";
  @SerializedName(SERIALIZED_NAME_DATE_OF_PURCHASE)
  private String dateOfPurchase;

  public static final String SERIALIZED_NAME_SHIP_DATE = "shipDate";
  @SerializedName(SERIALIZED_NAME_SHIP_DATE)
  private String shipDate;

  public static final String SERIALIZED_NAME_PRIMARY_SERIAL_NUMBER = "primarySerialNumber";
  @SerializedName(SERIALIZED_NAME_PRIMARY_SERIAL_NUMBER)
  private String primarySerialNumber;

  public static final String SERIALIZED_NAME_SECONDARY_SERIAL_NUMBER = "secondarySerialNumber";
  @SerializedName(SERIALIZED_NAME_SECONDARY_SERIAL_NUMBER)
  private String secondarySerialNumber;

  public AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner() {
  }

  public AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner dateOfPurchase(String dateOfPurchase) {
    this.dateOfPurchase = dateOfPurchase;
    return this;
  }

   /**
   * Get dateOfPurchase
   * @return dateOfPurchase
  **/
  @javax.annotation.Nullable
  public String getDateOfPurchase() {
    return dateOfPurchase;
  }

  public void setDateOfPurchase(String dateOfPurchase) {
    this.dateOfPurchase = dateOfPurchase;
  }


  public AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner shipDate(String shipDate) {
    this.shipDate = shipDate;
    return this;
  }

   /**
   * Get shipDate
   * @return shipDate
  **/
  @javax.annotation.Nullable
  public String getShipDate() {
    return shipDate;
  }

  public void setShipDate(String shipDate) {
    this.shipDate = shipDate;
  }


  public AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner primarySerialNumber(String primarySerialNumber) {
    this.primarySerialNumber = primarySerialNumber;
    return this;
  }

   /**
   * Get primarySerialNumber
   * @return primarySerialNumber
  **/
  @javax.annotation.Nullable
  public String getPrimarySerialNumber() {
    return primarySerialNumber;
  }

  public void setPrimarySerialNumber(String primarySerialNumber) {
    this.primarySerialNumber = primarySerialNumber;
  }


  public AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner secondarySerialNumber(String secondarySerialNumber) {
    this.secondarySerialNumber = secondarySerialNumber;
    return this;
  }

   /**
   * Get secondarySerialNumber
   * @return secondarySerialNumber
  **/
  @javax.annotation.Nullable
  public String getSecondarySerialNumber() {
    return secondarySerialNumber;
  }

  public void setSecondarySerialNumber(String secondarySerialNumber) {
    this.secondarySerialNumber = secondarySerialNumber;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner asyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner = (AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner) o;
    return Objects.equals(this.dateOfPurchase, asyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner.dateOfPurchase) &&
        Objects.equals(this.shipDate, asyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner.shipDate) &&
        Objects.equals(this.primarySerialNumber, asyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner.primarySerialNumber) &&
        Objects.equals(this.secondarySerialNumber, asyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner.secondarySerialNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateOfPurchase, shipDate, primarySerialNumber, secondarySerialNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner {\n");
    sb.append("    dateOfPurchase: ").append(toIndentedString(dateOfPurchase)).append("\n");
    sb.append("    shipDate: ").append(toIndentedString(shipDate)).append("\n");
    sb.append("    primarySerialNumber: ").append(toIndentedString(primarySerialNumber)).append("\n");
    sb.append("    secondarySerialNumber: ").append(toIndentedString(secondarySerialNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("dateOfPurchase");
    openapiFields.add("shipDate");
    openapiFields.add("primarySerialNumber");
    openapiFields.add("secondarySerialNumber");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner is not found in the empty JSON string", AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("dateOfPurchase") != null && !jsonObj.get("dateOfPurchase").isJsonNull()) && !jsonObj.get("dateOfPurchase").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dateOfPurchase` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dateOfPurchase").toString()));
      }
      if ((jsonObj.get("shipDate") != null && !jsonObj.get("shipDate").isJsonNull()) && !jsonObj.get("shipDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shipDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipDate").toString()));
      }
      if ((jsonObj.get("primarySerialNumber") != null && !jsonObj.get("primarySerialNumber").isJsonNull()) && !jsonObj.get("primarySerialNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `primarySerialNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primarySerialNumber").toString()));
      }
      if ((jsonObj.get("secondarySerialNumber") != null && !jsonObj.get("secondarySerialNumber").isJsonNull()) && !jsonObj.get("secondarySerialNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `secondarySerialNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secondarySerialNumber").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner.class));

       return (TypeAdapter<T>) new TypeAdapter<AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner>() {
           @Override
           public void write(JsonWriter out, AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner
  * @throws IOException if the JSON string is invalid with respect to AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner
  */
  public static AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner.class);
  }

 /**
  * Convert an instance of AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

