/*
 * Reseller API
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import xiresellers.client.JSON;

/**
 * OrderModifyRequestServicerequestRequestpreamble
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-22T11:06:29.712836Z[Etc/UTC]")
public class OrderModifyRequestServicerequestRequestpreamble {
  public static final String SERIALIZED_NAME_ISOCOUNTRYCODE = "isocountrycode";
  @SerializedName(SERIALIZED_NAME_ISOCOUNTRYCODE)
  private String isocountrycode;

  public static final String SERIALIZED_NAME_CUSTOMERNUMBER = "customernumber";
  @SerializedName(SERIALIZED_NAME_CUSTOMERNUMBER)
  private String customernumber;

  public OrderModifyRequestServicerequestRequestpreamble() {
  }

  public OrderModifyRequestServicerequestRequestpreamble isocountrycode(String isocountrycode) {
    this.isocountrycode = isocountrycode;
    return this;
  }

   /**
   * Get isocountrycode
   * @return isocountrycode
  **/
  @javax.annotation.Nullable
  public String getIsocountrycode() {
    return isocountrycode;
  }

  public void setIsocountrycode(String isocountrycode) {
    this.isocountrycode = isocountrycode;
  }


  public OrderModifyRequestServicerequestRequestpreamble customernumber(String customernumber) {
    this.customernumber = customernumber;
    return this;
  }

   /**
   * Get customernumber
   * @return customernumber
  **/
  @javax.annotation.Nullable
  public String getCustomernumber() {
    return customernumber;
  }

  public void setCustomernumber(String customernumber) {
    this.customernumber = customernumber;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderModifyRequestServicerequestRequestpreamble orderModifyRequestServicerequestRequestpreamble = (OrderModifyRequestServicerequestRequestpreamble) o;
    return Objects.equals(this.isocountrycode, orderModifyRequestServicerequestRequestpreamble.isocountrycode) &&
        Objects.equals(this.customernumber, orderModifyRequestServicerequestRequestpreamble.customernumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isocountrycode, customernumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderModifyRequestServicerequestRequestpreamble {\n");
    sb.append("    isocountrycode: ").append(toIndentedString(isocountrycode)).append("\n");
    sb.append("    customernumber: ").append(toIndentedString(customernumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("isocountrycode");
    openapiFields.add("customernumber");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OrderModifyRequestServicerequestRequestpreamble
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrderModifyRequestServicerequestRequestpreamble.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrderModifyRequestServicerequestRequestpreamble is not found in the empty JSON string", OrderModifyRequestServicerequestRequestpreamble.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OrderModifyRequestServicerequestRequestpreamble.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OrderModifyRequestServicerequestRequestpreamble` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("isocountrycode") != null && !jsonObj.get("isocountrycode").isJsonNull()) && !jsonObj.get("isocountrycode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isocountrycode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isocountrycode").toString()));
      }
      if ((jsonObj.get("customernumber") != null && !jsonObj.get("customernumber").isJsonNull()) && !jsonObj.get("customernumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customernumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customernumber").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrderModifyRequestServicerequestRequestpreamble.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrderModifyRequestServicerequestRequestpreamble' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrderModifyRequestServicerequestRequestpreamble> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrderModifyRequestServicerequestRequestpreamble.class));

       return (TypeAdapter<T>) new TypeAdapter<OrderModifyRequestServicerequestRequestpreamble>() {
           @Override
           public void write(JsonWriter out, OrderModifyRequestServicerequestRequestpreamble value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrderModifyRequestServicerequestRequestpreamble read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OrderModifyRequestServicerequestRequestpreamble given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OrderModifyRequestServicerequestRequestpreamble
  * @throws IOException if the JSON string is invalid with respect to OrderModifyRequestServicerequestRequestpreamble
  */
  public static OrderModifyRequestServicerequestRequestpreamble fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrderModifyRequestServicerequestRequestpreamble.class);
  }

 /**
  * Convert an instance of OrderModifyRequestServicerequestRequestpreamble to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

