/*
 * Reseller API
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import xiresellers.client.JSON;

/**
 * OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-22T11:06:29.712836Z[Etc/UTC]")
public class OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner {
  /**
   * Gets or Sets attributename
   */
  @JsonAdapter(AttributenameEnum.Adapter.class)
  public enum AttributenameEnum {
    SHIPFROM("shipfrom"),
    
    SPECIALPRICE("specialprice"),
    
    AUTHBIDNUMBER("authbidnumber"),
    
    COMMENTTEXT("commenttext"),
    
    SERIALNUMBER("serialnumber"),
    
    CONTACTNUMBER("contactnumber"),
    
    SHIPNOTESTXT("shipnotestxt");

    private String value;

    AttributenameEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AttributenameEnum fromValue(String value) {
      for (AttributenameEnum b : AttributenameEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AttributenameEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AttributenameEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AttributenameEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AttributenameEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AttributenameEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ATTRIBUTENAME = "attributename";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTENAME)
  private AttributenameEnum attributename;

  public static final String SERIALIZED_NAME_ATTRIBUTEVALUE = "attributevalue";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTEVALUE)
  private String attributevalue;

  public OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner() {
  }

  public OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner attributename(AttributenameEnum attributename) {
    this.attributename = attributename;
    return this;
  }

   /**
   * Get attributename
   * @return attributename
  **/
  @javax.annotation.Nullable
  public AttributenameEnum getAttributename() {
    return attributename;
  }

  public void setAttributename(AttributenameEnum attributename) {
    this.attributename = attributename;
  }


  public OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner attributevalue(String attributevalue) {
    this.attributevalue = attributevalue;
    return this;
  }

   /**
   * Get attributevalue
   * @return attributevalue
  **/
  @javax.annotation.Nullable
  public String getAttributevalue() {
    return attributevalue;
  }

  public void setAttributevalue(String attributevalue) {
    this.attributevalue = attributevalue;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner orderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner = (OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner) o;
    return Objects.equals(this.attributename, orderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner.attributename) &&
        Objects.equals(this.attributevalue, orderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner.attributevalue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributename, attributevalue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner {\n");
    sb.append("    attributename: ").append(toIndentedString(attributename)).append("\n");
    sb.append("    attributevalue: ").append(toIndentedString(attributevalue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("attributename");
    openapiFields.add("attributevalue");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner is not found in the empty JSON string", OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("attributename") != null && !jsonObj.get("attributename").isJsonNull()) && !jsonObj.get("attributename").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `attributename` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attributename").toString()));
      }
      // validate the optional field `attributename`
      if (jsonObj.get("attributename") != null && !jsonObj.get("attributename").isJsonNull()) {
        AttributenameEnum.validateJsonElement(jsonObj.get("attributename"));
      }
      if ((jsonObj.get("attributevalue") != null && !jsonObj.get("attributevalue").isJsonNull()) && !jsonObj.get("attributevalue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `attributevalue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attributevalue").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner>() {
           @Override
           public void write(JsonWriter out, OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner
  * @throws IOException if the JSON string is invalid with respect to OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner
  */
  public static OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner.class);
  }

 /**
  * Convert an instance of OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerProductextendedspecsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

