/*
 * Reseller API
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xiresellers.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import xiresellers.client.JSON;

/**
 * PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-19T11:54:36.350241Z[Etc/UTC]")
public class PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner {
  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_INDEX)
  private Integer index;

  public static final String SERIALIZED_NAME_INGRAMPARTNUMBER = "ingrampartnumber";
  @SerializedName(SERIALIZED_NAME_INGRAMPARTNUMBER)
  private String ingrampartnumber;

  public static final String SERIALIZED_NAME_VENDORPARTNUMBER = "vendorpartnumber";
  @SerializedName(SERIALIZED_NAME_VENDORPARTNUMBER)
  private String vendorpartnumber;

  public static final String SERIALIZED_NAME_UPC = "upc";
  @SerializedName(SERIALIZED_NAME_UPC)
  private String upc;

  public static final String SERIALIZED_NAME_CUSTOMERPARTNUMBER = "customerpartnumber";
  @SerializedName(SERIALIZED_NAME_CUSTOMERPARTNUMBER)
  private String customerpartnumber;

  public static final String SERIALIZED_NAME_WAREHOUSEIDLIST = "warehouseidlist";
  @SerializedName(SERIALIZED_NAME_WAREHOUSEIDLIST)
  private List<String> warehouseidlist;

  public static final String SERIALIZED_NAME_EXTENDEDVENDORPARTNUMBER = "extendedvendorpartnumber";
  @SerializedName(SERIALIZED_NAME_EXTENDEDVENDORPARTNUMBER)
  private String extendedvendorpartnumber;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private BigDecimal quantity;

  public static final String SERIALIZED_NAME_ENDUSERID = "enduserid";
  @SerializedName(SERIALIZED_NAME_ENDUSERID)
  private String enduserid;

  public static final String SERIALIZED_NAME_GOVTPROGRAMTYPE = "govtprogramtype";
  @SerializedName(SERIALIZED_NAME_GOVTPROGRAMTYPE)
  private String govtprogramtype;

  public static final String SERIALIZED_NAME_GOVTENDUSERTYPE = "govtendusertype";
  @SerializedName(SERIALIZED_NAME_GOVTENDUSERTYPE)
  private String govtendusertype;

  public static final String SERIALIZED_NAME_SPECIALBIDNUMBER = "specialbidnumber";
  @SerializedName(SERIALIZED_NAME_SPECIALBIDNUMBER)
  private String specialbidnumber;

  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner() {
  }

  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Get index
   * @return index
  **/
  @javax.annotation.Nullable
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }


  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner ingrampartnumber(String ingrampartnumber) {
    this.ingrampartnumber = ingrampartnumber;
    return this;
  }

   /**
   * Ingram Micro SKU number
   * @return ingrampartnumber
  **/
  @javax.annotation.Nullable
  public String getIngrampartnumber() {
    return ingrampartnumber;
  }

  public void setIngrampartnumber(String ingrampartnumber) {
    this.ingrampartnumber = ingrampartnumber;
  }


  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner vendorpartnumber(String vendorpartnumber) {
    this.vendorpartnumber = vendorpartnumber;
    return this;
  }

   /**
   * Vendor/Manufacture Part Number
   * @return vendorpartnumber
  **/
  @javax.annotation.Nullable
  public String getVendorpartnumber() {
    return vendorpartnumber;
  }

  public void setVendorpartnumber(String vendorpartnumber) {
    this.vendorpartnumber = vendorpartnumber;
  }


  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner upc(String upc) {
    this.upc = upc;
    return this;
  }

   /**
   * Universal Product code
   * @return upc
  **/
  @javax.annotation.Nullable
  public String getUpc() {
    return upc;
  }

  public void setUpc(String upc) {
    this.upc = upc;
  }


  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner customerpartnumber(String customerpartnumber) {
    this.customerpartnumber = customerpartnumber;
    return this;
  }

   /**
   * Unique identoifier for the customer, needs custom setup.
   * @return customerpartnumber
  **/
  @javax.annotation.Nullable
  public String getCustomerpartnumber() {
    return customerpartnumber;
  }

  public void setCustomerpartnumber(String customerpartnumber) {
    this.customerpartnumber = customerpartnumber;
  }


  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner warehouseidlist(List<String> warehouseidlist) {
    this.warehouseidlist = warehouseidlist;
    return this;
  }

  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner addWarehouseidlistItem(String warehouseidlistItem) {
    if (this.warehouseidlist == null) {
      this.warehouseidlist = new ArrayList<>();
    }
    this.warehouseidlist.add(warehouseidlistItem);
    return this;
  }

   /**
   * Unique identity for Ingram Micro warehouses against which stock details are returned.
   * @return warehouseidlist
  **/
  @javax.annotation.Nullable
  public List<String> getWarehouseidlist() {
    return warehouseidlist;
  }

  public void setWarehouseidlist(List<String> warehouseidlist) {
    this.warehouseidlist = warehouseidlist;
  }


  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner extendedvendorpartnumber(String extendedvendorpartnumber) {
    this.extendedvendorpartnumber = extendedvendorpartnumber;
    return this;
  }

   /**
   * Get extendedvendorpartnumber
   * @return extendedvendorpartnumber
  **/
  @javax.annotation.Nullable
  public String getExtendedvendorpartnumber() {
    return extendedvendorpartnumber;
  }

  public void setExtendedvendorpartnumber(String extendedvendorpartnumber) {
    this.extendedvendorpartnumber = extendedvendorpartnumber;
  }


  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner quantity(BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @javax.annotation.Nullable
  public BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }


  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner enduserid(String enduserid) {
    this.enduserid = enduserid;
    return this;
  }

   /**
   * Get enduserid
   * @return enduserid
  **/
  @javax.annotation.Nullable
  public String getEnduserid() {
    return enduserid;
  }

  public void setEnduserid(String enduserid) {
    this.enduserid = enduserid;
  }


  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner govtprogramtype(String govtprogramtype) {
    this.govtprogramtype = govtprogramtype;
    return this;
  }

   /**
   * Get govtprogramtype
   * @return govtprogramtype
  **/
  @javax.annotation.Nullable
  public String getGovtprogramtype() {
    return govtprogramtype;
  }

  public void setGovtprogramtype(String govtprogramtype) {
    this.govtprogramtype = govtprogramtype;
  }


  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner govtendusertype(String govtendusertype) {
    this.govtendusertype = govtendusertype;
    return this;
  }

   /**
   * Get govtendusertype
   * @return govtendusertype
  **/
  @javax.annotation.Nullable
  public String getGovtendusertype() {
    return govtendusertype;
  }

  public void setGovtendusertype(String govtendusertype) {
    this.govtendusertype = govtendusertype;
  }


  public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner specialbidnumber(String specialbidnumber) {
    this.specialbidnumber = specialbidnumber;
    return this;
  }

   /**
   * Get specialbidnumber
   * @return specialbidnumber
  **/
  @javax.annotation.Nullable
  public String getSpecialbidnumber() {
    return specialbidnumber;
  }

  public void setSpecialbidnumber(String specialbidnumber) {
    this.specialbidnumber = specialbidnumber;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner = (PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner) o;
    return Objects.equals(this.index, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.index) &&
        Objects.equals(this.ingrampartnumber, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.ingrampartnumber) &&
        Objects.equals(this.vendorpartnumber, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.vendorpartnumber) &&
        Objects.equals(this.upc, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.upc) &&
        Objects.equals(this.customerpartnumber, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.customerpartnumber) &&
        Objects.equals(this.warehouseidlist, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.warehouseidlist) &&
        Objects.equals(this.extendedvendorpartnumber, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.extendedvendorpartnumber) &&
        Objects.equals(this.quantity, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.quantity) &&
        Objects.equals(this.enduserid, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.enduserid) &&
        Objects.equals(this.govtprogramtype, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.govtprogramtype) &&
        Objects.equals(this.govtendusertype, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.govtendusertype) &&
        Objects.equals(this.specialbidnumber, priceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.specialbidnumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, ingrampartnumber, vendorpartnumber, upc, customerpartnumber, warehouseidlist, extendedvendorpartnumber, quantity, enduserid, govtprogramtype, govtendusertype, specialbidnumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    ingrampartnumber: ").append(toIndentedString(ingrampartnumber)).append("\n");
    sb.append("    vendorpartnumber: ").append(toIndentedString(vendorpartnumber)).append("\n");
    sb.append("    upc: ").append(toIndentedString(upc)).append("\n");
    sb.append("    customerpartnumber: ").append(toIndentedString(customerpartnumber)).append("\n");
    sb.append("    warehouseidlist: ").append(toIndentedString(warehouseidlist)).append("\n");
    sb.append("    extendedvendorpartnumber: ").append(toIndentedString(extendedvendorpartnumber)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    enduserid: ").append(toIndentedString(enduserid)).append("\n");
    sb.append("    govtprogramtype: ").append(toIndentedString(govtprogramtype)).append("\n");
    sb.append("    govtendusertype: ").append(toIndentedString(govtendusertype)).append("\n");
    sb.append("    specialbidnumber: ").append(toIndentedString(specialbidnumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("index");
    openapiFields.add("ingrampartnumber");
    openapiFields.add("vendorpartnumber");
    openapiFields.add("upc");
    openapiFields.add("customerpartnumber");
    openapiFields.add("warehouseidlist");
    openapiFields.add("extendedvendorpartnumber");
    openapiFields.add("quantity");
    openapiFields.add("enduserid");
    openapiFields.add("govtprogramtype");
    openapiFields.add("govtendusertype");
    openapiFields.add("specialbidnumber");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner is not found in the empty JSON string", PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("ingrampartnumber") != null && !jsonObj.get("ingrampartnumber").isJsonNull()) && !jsonObj.get("ingrampartnumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ingrampartnumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ingrampartnumber").toString()));
      }
      if ((jsonObj.get("vendorpartnumber") != null && !jsonObj.get("vendorpartnumber").isJsonNull()) && !jsonObj.get("vendorpartnumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vendorpartnumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vendorpartnumber").toString()));
      }
      if ((jsonObj.get("upc") != null && !jsonObj.get("upc").isJsonNull()) && !jsonObj.get("upc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `upc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("upc").toString()));
      }
      if ((jsonObj.get("customerpartnumber") != null && !jsonObj.get("customerpartnumber").isJsonNull()) && !jsonObj.get("customerpartnumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerpartnumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerpartnumber").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("warehouseidlist") != null && !jsonObj.get("warehouseidlist").isJsonNull() && !jsonObj.get("warehouseidlist").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `warehouseidlist` to be an array in the JSON string but got `%s`", jsonObj.get("warehouseidlist").toString()));
      }
      if ((jsonObj.get("extendedvendorpartnumber") != null && !jsonObj.get("extendedvendorpartnumber").isJsonNull()) && !jsonObj.get("extendedvendorpartnumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `extendedvendorpartnumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("extendedvendorpartnumber").toString()));
      }
      if ((jsonObj.get("enduserid") != null && !jsonObj.get("enduserid").isJsonNull()) && !jsonObj.get("enduserid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `enduserid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("enduserid").toString()));
      }
      if ((jsonObj.get("govtprogramtype") != null && !jsonObj.get("govtprogramtype").isJsonNull()) && !jsonObj.get("govtprogramtype").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `govtprogramtype` to be a primitive type in the JSON string but got `%s`", jsonObj.get("govtprogramtype").toString()));
      }
      if ((jsonObj.get("govtendusertype") != null && !jsonObj.get("govtendusertype").isJsonNull()) && !jsonObj.get("govtendusertype").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `govtendusertype` to be a primitive type in the JSON string but got `%s`", jsonObj.get("govtendusertype").toString()));
      }
      if ((jsonObj.get("specialbidnumber") != null && !jsonObj.get("specialbidnumber").isJsonNull()) && !jsonObj.get("specialbidnumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `specialbidnumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("specialbidnumber").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.class));

       return (TypeAdapter<T>) new TypeAdapter<PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner>() {
           @Override
           public void write(JsonWriter out, PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner
  * @throws IOException if the JSON string is invalid with respect to PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner
  */
  public static PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner.class);
  }

 /**
  * Convert an instance of PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

